### ISSUE TITLE
Selection feedback is lost when modifying a property

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#328] opened 2023-11-13 08:00 UTC
### Describe the Bug

Selection feedback is lost when modifying a property

### Steps to Reproduce the Bug or Issue

- select a node
- notice the selection feedback on the node
- modify a value in the property panel
--> the selection feedback is removed

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/1105127/17ff738c-ea1d-4e27-99ea-d4f5988ef011

### Platform

- OS: Linux
- Browser: Firefox
- Version: main

**Comment by apupier** [comment] 2023-11-13 08:06
might be a side-effect only of https://github.com/KaotoIO/kaoto-next/issues/213

**Comment by lordrip** [comment] 2023-11-20 18:57
This issue it's a byproduct of #213  but the root cause of it is #266.

**Comment by lordrip** [comment] 2023-11-20 18:57
Fixed with https://github.com/KaotoIO/kaoto-next/pull/325

**Closed by lordrip** 2023-11-20 18:57 UTC
Labels: bug
